/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Clases.*;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author jsoto
 */
public class PanelDistribuidor extends javax.swing.JPanel {

    /**
     * Creates new form AgregarIdioma
     */
    public PanelDistribuidor() {
        initComponents();
        
        tableTablaDatos.getTableHeader().setReorderingAllowed(false);
        BDDistribuidor.listar(tableTablaDatos);
        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);
    }
        
    /**
     * Método para habilitar y deshabilitar botones de acción
     */
    public void comprobarCampos(){
        String cc = txtNumRut.getText() + txtDigRut.getText() + txtNombre.getText() + txtDireccion.getText() + txtTelefono.getText();
        if ( cc.equals("")){
            btnGuardar.setEnabled(false);
            btnLimpiar.setEnabled(false);            
        }else if (txtNumRut.getText().isEmpty() || txtDigRut.getText().isEmpty() || txtNombre.getText().isEmpty() || 
                txtDireccion.getText().isEmpty() || txtTelefono.getText().isEmpty()) {
            btnGuardar.setEnabled(false);
            btnLimpiar.setEnabled(true);
        }else{
            btnGuardar.setEnabled(true);
            btnLimpiar.setEnabled(true);
        }
        
        //Se activan o desactivan botones
        if (tableTablaDatos.getSelectedRow() == -1){
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }else{
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }
    
    /**
     * Método para obtener los campos del item seleccionado en la tabla principal
     */
    public void obtenerCampos(){
        //Se obtienen datos de fila seleccionada en la tabla y se cargan los campos correspondientes
        int rowSel = tableTablaDatos.getSelectedRow();
        lblID.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 0)));
        String rut = String.valueOf(tableTablaDatos.getValueAt(rowSel, 1));
        String numRut = rut.substring(0, rut.length()-2);
        String digRut = rut.substring(rut.length()-1);
        txtNumRut.setText(numRut);
        txtDigRut.setText(digRut);
        txtNombre.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 2)));
        txtDireccion.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 3)));
        txtTelefono.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 4)));
        jYearAnio.setValue((Integer) tableTablaDatos.getValueAt(rowSel, 5));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        lblTitulo = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTablaDatos = new javax.swing.JTable();
        panelSuperiorBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelCampos = new javax.swing.JPanel();
        lblEtiquetaID = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        txtNumRut = new javax.swing.JTextField();
        txtDigRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jYearAnio = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        panelInferiorBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelFiltrar = new javax.swing.JPanel();
        jComboBoxItemBusqueda = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnQuitarFiltro = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 570));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(800, 570));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("DISTRIBUIDORES");

        panelTabla.setMaximumSize(new java.awt.Dimension(780, 140));
        panelTabla.setMinimumSize(new java.awt.Dimension(780, 140));
        panelTabla.setPreferredSize(new java.awt.Dimension(780, 140));

        tableTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Nombre", "Dirección", "Teléfono", "Año inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTablaDatosMouseClicked(evt);
            }
        });
        tableTablaDatos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tableTablaDatosCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tableTablaDatos);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnAgregar);

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnModificar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnModificar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnEliminar);

        panelCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEtiquetaID.setText("ID");

        lblRut.setText("Rut");

        lblNombre.setText("Nombre");

        lblDireccion.setText("Dirección");

        lblTelefono.setText("Teléfono");

        lblAnio.setText("Año Inicio");

        txtNumRut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumRutActionPerformed(evt);
            }
        });
        txtNumRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumRutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumRutKeyTyped(evt);
            }
        });

        txtDigRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigRutActionPerformed(evt);
            }
        });
        txtDigRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDigRutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDigRutKeyTyped(evt);
            }
        });

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jYearAnio.setEndYear(anioActual);
        jYearAnio.setStartYear(2000);
        jYearAnio.setValue(0);
        jYearAnio.setYear(0);

        jLabel2.setText("-");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRut)
                    .addComponent(lblNombre)
                    .addComponent(lblDireccion)
                    .addComponent(lblEtiquetaID))
                .addGap(37, 37, 37)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addComponent(txtNumRut, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDigRut, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addComponent(txtNombre)
                        .addComponent(txtDireccion))
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnio)
                    .addComponent(lblTelefono))
                .addGap(42, 42, 42)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jYearAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtTelefono))
                .addGap(186, 186, 186))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEtiquetaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addGap(18, 18, 18)
                        .addComponent(jYearAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDigRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblRut))
                        .addGap(18, 18, 18)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre)
                            .addComponent(lblAnio))
                        .addGap(18, 18, 18)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnGuardar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnLimpiar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnCancelar);

        jComboBoxItemBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rut", "Nombre" }));
        jComboBoxItemBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemBusquedaActionPerformed(evt);
            }
        });
        panelFiltrar.add(jComboBoxItemBusqueda);

        txtBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        panelFiltrar.add(txtBusqueda);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setMaximumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setMinimumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnFiltrar);

        btnQuitarFiltro.setText("Quitar filtro");
        btnQuitarFiltro.setMaximumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setMinimumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setPreferredSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarFiltroActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnQuitarFiltro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSuperiorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                            .addComponent(panelFiltrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelInferiorBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSuperiorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferiorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Se agrega o modifica registro según botón seleccionado.
        try{            
            String rut = txtNumRut.getText() + "-" + txtDigRut.getText();
            String nom = txtNombre.getText();
            String dir = txtDireccion.getText();
            int tel = Integer.parseInt(txtTelefono.getText());
            int anio = jYearAnio.getValue();
            if(btnAgregar.isSelected()){
                BDDistribuidor.insertar(rut, nom, dir, tel, anio);
                BDDistribuidor.listar(tableTablaDatos);
                Limpiar.contenidoPanel(panelCampos);
                comprobarCampos();
            }else if(btnModificar.isSelected()){
                int id = Integer.parseInt(lblID.getText());
                BDDistribuidor.modificar(id, rut, nom, dir, tel, anio);
                BDDistribuidor.listar(tableTablaDatos);
                Limpiar.contenidoPanel(panelCampos);
                comprobarCampos();
            }
        }catch(Exception e){
            System.err.println("Excepción al guardar : " + e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        btnAgregar.setSelected(true);
        btnAgregar.setBackground(Color.GRAY);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
        Limpiar.contenidoPanel(panelCampos);
        lblID.setText("");
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtNumRut.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        txtTelefono.requestFocus();
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtNumRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumRutActionPerformed
        txtDigRut.requestFocus();
    }//GEN-LAST:event_txtNumRutActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtDireccion.requestFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar.contenidoPanel(panelCampos);
        comprobarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar.contenidoPanel(panelCampos);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Se activa selección de botón Modificar y de desactiva botón Agregar
        btnModificar.setSelected(true);
        btnModificar.setBackground(Color.GRAY);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);
        //Se limpian campos
        Limpiar.contenidoPanel(panelCampos);
        
        //Se obtienen datos de fila seleccionada en la tabla y se cargan los campos correspondientes
        obtenerCampos();
        
        comprobarCampos();
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtNumRut.requestFocus();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if ( respuesta == 0){
            //Se obtiene ID para eliminar registro
            int rowSel = tableTablaDatos.getSelectedRow();
            int reg = (Integer) tableTablaDatos.getValueAt(rowSel, 0);
            System.out.println("ID :" + reg);
            BDDistribuidor.eliminar(reg);
            BDDistribuidor.listar(tableTablaDatos);
            Limpiar.contenidoPanel(panelCampos);
            lblID.setText("");
        }        
        comprobarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDigRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigRutActionPerformed
        txtNombre.requestFocus();
    }//GEN-LAST:event_txtDigRutActionPerformed

    private void txtNumRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumRutKeyTyped
        int limite = 8;
        if ( txtNumRut.getText().length() >= limite){
            evt.consume();
        }
        char enter = evt.getKeyChar();
        if ( !(Character.isDigit(enter))){
            evt.consume();
        }        
    }//GEN-LAST:event_txtNumRutKeyTyped

    private void txtDigRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigRutKeyTyped
        //Limite de campo de text
        int limite = 1;
        if ( txtDigRut.getText().length() >= limite){
            evt.consume();
        }
        //Solo se acepta numero o caracter "k"
        char enter = evt.getKeyChar();
        if ( !(Character.isDigit(enter)) && !String.valueOf(enter).toLowerCase().equals("k")){
            evt.consume();
        }
    }//GEN-LAST:event_txtDigRutKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int largo = 40;
        if (txtNombre.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 40 caracteres");
        }        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        int largo = 60;
        if (txtDireccion.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 60 caracteres");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        btnFiltrar.requestFocus();
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        int largo = 60;
        if (txtDireccion.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 60 caracteres");
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jComboBoxItemBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxItemBusquedaActionPerformed

    private void txtNumRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumRutKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtNumRutKeyReleased

    private void txtDigRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigRutKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtDigRutKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void tableTablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTablaDatosMouseClicked
        //Al seleccionar item de la tabla, se actualizan campos y se activa botón Modificar
        if(btnAgregar.isSelected()){
            btnAgregar.setSelected(false);
            btnAgregar.setBackground(null);
            btnModificar.setSelected(true);
            btnModificar.setBackground(Color.GRAY);
        }
        comprobarCampos();
        obtenerCampos();
    }//GEN-LAST:event_tableTablaDatosMouseClicked

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        jYearAnio.requestFocus();
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String criterioBusqueda = jComboBoxItemBusqueda.getSelectedItem().toString();
        String textoBusqueda = txtBusqueda.getText();
        System.out.println("Campo a buscar: " + criterioBusqueda);
        System.out.println("Criterio a buscar: " + criterioBusqueda);
        
        if (criterioBusqueda.equals("Rut")){
            BDDistribuidor.filtrar(tableTablaDatos, "rut_distribuidor", textoBusqueda);
        }else if (criterioBusqueda.equals("Nombre")){
            BDDistribuidor.filtrar(tableTablaDatos, "nombre_distribuidor", textoBusqueda);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        long limite = 9;
        if ( txtTelefono.getText().length() >= limite){
            evt.consume();
        }
        char enter = evt.getKeyChar();
        if ( !(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFiltroActionPerformed
        txtBusqueda.setText("");
        BDDistribuidor.listar(tableTablaDatos);
        comprobarCampos();
    }//GEN-LAST:event_btnQuitarFiltroActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        txtNombre.setText(txtNombre.getText().toUpperCase());
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        txtDireccion.setText(txtDireccion.getText().toUpperCase());
    }//GEN-LAST:event_txtDireccionFocusLost

    private void tableTablaDatosCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableTablaDatosCaretPositionChanged
        //Al seleccionar item de la tabla, se actualizan campos y se activa botón Modificar
        if(btnAgregar.isSelected()){
            btnAgregar.setSelected(false);
            btnAgregar.setBackground(null);
            btnModificar.setSelected(true);
            btnModificar.setBackground(Color.GRAY);
        }
        comprobarCampos();
        obtenerCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_tableTablaDatosCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarFiltro;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> jComboBoxItemBusqueda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYearAnio;
    Calendar cal= Calendar.getInstance();
    int anioActual= cal.get(Calendar.YEAR);
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEtiquetaID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelFiltrar;
    private javax.swing.JPanel panelInferiorBotones;
    private javax.swing.JPanel panelSuperiorBotones;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tableTablaDatos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDigRut;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
