/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Clases.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jsoto
 */
public class PanelAutor extends javax.swing.JPanel {

    /**
     * Creates new form PanelAutor
     */
    public PanelAutor() {
        initComponents();

        tableTablaDatos.getTableHeader().setReorderingAllowed(false);
        BDAutor.listar(tableTablaDatos);
        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);
    }

   
    /**
     * Método para comprobar los campos, habilitar y deshabilitar botones de acción
     */
    public void comprobarCampos(){
        String cc = txtNombre.getText() + txtApellidoP.getText() + txtApellidoM.getText();
        if ( cc.equals("")){
            btnGuardar.setEnabled(false);
            btnLimpiar.setEnabled(false);            
        }else if (txtNombre.getText().isEmpty() || txtApellidoP.getText().isEmpty() || txtApellidoM.getText().isEmpty()) {
            btnGuardar.setEnabled(false);
            btnLimpiar.setEnabled(true);
        }else{
            btnGuardar.setEnabled(true);
            btnLimpiar.setEnabled(true);
        }
        if (tableTablaDatos.getSelectedRow() == -1){
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }else{
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }
        
    public void obtenerCampos(){
        int rowSel = tableTablaDatos.getSelectedRow();
        lblID.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 0)));
        txtNombre.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 1)));
        txtApellidoP.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 2)));
        txtApellidoM.setText(String.valueOf(tableTablaDatos.getValueAt(rowSel, 3)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        lblTitulo = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTablaDatos = new javax.swing.JTable();
        panelCampos = new javax.swing.JPanel();
        lblEtiquetaID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        panelSuperiorBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelInferiorBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 570));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(800, 570));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("AUTORES");
        lblTitulo.setMaximumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setMinimumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setPreferredSize(new java.awt.Dimension(780, 44));

        panelTabla.setMaximumSize(new java.awt.Dimension(780, 140));
        panelTabla.setMinimumSize(new java.awt.Dimension(780, 140));
        panelTabla.setPreferredSize(new java.awt.Dimension(780, 140));
        panelTabla.setLayout(new javax.swing.BoxLayout(panelTabla, javax.swing.BoxLayout.LINE_AXIS));

        tableTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTablaDatos);

        panelTabla.add(jScrollPane1);

        panelCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCampos.setMaximumSize(new java.awt.Dimension(780, 266));
        panelCampos.setMinimumSize(new java.awt.Dimension(780, 266));
        panelCampos.setPreferredSize(new java.awt.Dimension(780, 266));

        lblEtiquetaID.setText("ID");

        lblNombre.setText("Nombre");

        lblApellidoP.setText("Apellido paterno");

        lblApellidoM.setText("Apellido materno");

        txtNombre.setToolTipText("Máximo de 20 caracteres");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellidoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoPFocusLost(evt);
            }
        });
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyTyped(evt);
            }
        });

        txtApellidoM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoMFocusLost(evt);
            }
        });
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoP)
                    .addComponent(lblApellidoM)
                    .addComponent(lblNombre)
                    .addComponent(lblEtiquetaID))
                .addGap(30, 30, 30)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(txtApellidoP)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEtiquetaID)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoP)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoM)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        panelSuperiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelSuperiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));

        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnAgregar);

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnModificar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnModificar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnEliminar);

        panelInferiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelInferiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnGuardar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnLimpiar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSuperiorBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInferiorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSuperiorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferiorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        btnAgregar.setSelected(true);
        btnAgregar.setBackground(Color.GRAY);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
        Limpiar.contenidoPanel(panelCampos);
        lblID.setText("");
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Se activa selección de botón Modificar y de desactiva botón Agregar
        btnModificar.setSelected(true);
        btnModificar.setBackground(Color.GRAY);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);
        
        //Se limpian campos:
        Limpiar.contenidoPanel(panelCampos);
        
        //Se obtienen datos de fila seleccionada en la tabla y se cargan los campos correspondientes
        obtenerCampos();
        
        comprobarCampos();
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtNombre.requestFocus();
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if ( respuesta == 0){
            //Se obtiene ID para eliminar registro
            int rowSel = tableTablaDatos.getSelectedRow();
            int reg = (Integer) tableTablaDatos.getValueAt(rowSel, 0);
            BDAutor.eliminar(reg);
            BDAutor.listar(tableTablaDatos);
            Limpiar.contenidoPanel(panelCampos);
            lblID.setText("");            
        }        
        comprobarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtApellidoP.requestFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        txtApellidoM.requestFocus();
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        btnAgregar.requestFocus();
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        txtNombre.setText(txtNombre.getText().toUpperCase());
        comprobarCampos();
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPFocusLost
        txtApellidoP.setText(txtApellidoP.getText().toUpperCase());
        comprobarCampos();
    }//GEN-LAST:event_txtApellidoPFocusLost

    private void txtApellidoMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMFocusLost
        txtApellidoM.setText(txtApellidoM.getText().toUpperCase());
        comprobarCampos();
    }//GEN-LAST:event_txtApellidoMFocusLost

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int largo = 20;
        if (txtNombre.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 20 caracteres");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyTyped
        int largo = 20;
        if (txtApellidoP.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 20 caracteres");
        }
    }//GEN-LAST:event_txtApellidoPKeyTyped

    private void txtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyTyped
        int largo = 20;
        if (txtApellidoM.getText().length()>=largo) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 20 caracteres");
        }        
    }//GEN-LAST:event_txtApellidoMKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar.contenidoPanel(panelCampos);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Se limpias campos
        Limpiar.contenidoPanel(panelCampos);
        comprobarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Se agrega o modifica registro según botón seleccionado.
        try{            
            String nom = txtNombre.getText();
            String apeP = txtApellidoP.getText();
            String apeM = txtApellidoM.getText();

            if(btnAgregar.isSelected()){
                BDAutor.insertar(nom, apeP, apeM);
                BDAutor.listar(tableTablaDatos);
                Limpiar.contenidoPanel(panelCampos);
                comprobarCampos();
            }else if(btnModificar.isSelected()){
                int id = Integer.parseInt(lblID.getText());
                BDAutor.modificar(id, nom, apeP, apeM);
                BDAutor.listar(tableTablaDatos);
                Limpiar.contenidoPanel(panelCampos);
                comprobarCampos();
            }
        }catch(Exception e){
            System.err.println("Excepción al guardar : " + e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtApellidoPKeyReleased

    private void txtApellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyReleased
        comprobarCampos();
    }//GEN-LAST:event_txtApellidoMKeyReleased

    private void tableTablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTablaDatosMouseClicked
        //Al seleccionar item de la tabla, se actualizan campos y se activa botón Modificar
        if(btnAgregar.isSelected()){
            btnAgregar.setSelected(false);
            btnAgregar.setBackground(null);
            btnModificar.setSelected(true);
            btnModificar.setBackground(Color.GRAY);
        }
        comprobarCampos();
        obtenerCampos();
    }//GEN-LAST:event_tableTablaDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblEtiquetaID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelInferiorBotones;
    private javax.swing.JPanel panelSuperiorBotones;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tableTablaDatos;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
