/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

//import static Clases.BDLibro.listadoLibros;
import Clases.BDLibro;
import Clases.Libro;
import java.awt.BorderLayout;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author jsoto
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
//    public static List<Libro> listadoLibros;
    
    
    
    
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
//        BDLibro.generarListadoLibros();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestor = new javax.swing.JMenu();
        jMenuItemRegistro = new javax.swing.JMenuItem();
        jMenuItemAdminLibros = new javax.swing.JMenuItem();
        jMenuFacturas = new javax.swing.JMenu();
        jMenuItemFactura = new javax.swing.JMenuItem();
        jMenuMantenedor = new javax.swing.JMenu();
        jMenuItemAutor = new javax.swing.JMenuItem();
        jMenuItemDistribuidor = new javax.swing.JMenuItem();
        jMenuItemEditorial = new javax.swing.JMenuItem();
        jMenuItemLibros = new javax.swing.JMenuItem();
        jMenuItemMantenedor = new javax.swing.JMenuItem();
        jMenuCuenta = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanelContenido.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanelContenido.setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoFD.png"))); // NOI18N

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(74, 30));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(29, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(74, 30));

        jMenuGestor.setText("GESTOR");
        jMenuGestor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestorActionPerformed(evt);
            }
        });

        jMenuItemRegistro.setText("REGISTRO DE COMPRAS");
        jMenuItemRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroActionPerformed(evt);
            }
        });
        jMenuGestor.add(jMenuItemRegistro);

        jMenuItemAdminLibros.setText("ADMINISTRAR LIBROS");
        jMenuItemAdminLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminLibrosActionPerformed(evt);
            }
        });
        jMenuGestor.add(jMenuItemAdminLibros);

        jMenuBar1.add(jMenuGestor);

        jMenuFacturas.setText("CONSULTAS");
        jMenuFacturas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFacturasActionPerformed(evt);
            }
        });

        jMenuItemFactura.setText("FACTURAS");
        jMenuItemFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacturaActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jMenuItemFactura);

        jMenuBar1.add(jMenuFacturas);

        jMenuMantenedor.setText("MANTENEDOR");
        jMenuMantenedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuMantenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMantenedorActionPerformed(evt);
            }
        });

        jMenuItemAutor.setText("AUTORES");
        jMenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutorActionPerformed(evt);
            }
        });
        jMenuMantenedor.add(jMenuItemAutor);

        jMenuItemDistribuidor.setText("DISTRIBUIDORES");
        jMenuItemDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDistribuidorActionPerformed(evt);
            }
        });
        jMenuMantenedor.add(jMenuItemDistribuidor);

        jMenuItemEditorial.setText("EDITORIALES");
        jMenuItemEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditorialActionPerformed(evt);
            }
        });
        jMenuMantenedor.add(jMenuItemEditorial);

        jMenuItemLibros.setText("LIBROS");
        jMenuItemLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibrosActionPerformed(evt);
            }
        });
        jMenuMantenedor.add(jMenuItemLibros);

        jMenuItemMantenedor.setText("OTRAS ENTIDADES");
        jMenuItemMantenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantenedorActionPerformed(evt);
            }
        });
        jMenuMantenedor.add(jMenuItemMantenedor);

        jMenuBar1.add(jMenuMantenedor);

        jMenuCuenta.setText("SESION");
        jMenuCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemCerrarSesion.setText("CERRAR SESION");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuCuenta.add(jMenuItemCerrarSesion);

        jMenuItemSalir.setText("SALIR");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuCuenta.add(jMenuItemSalir);

        jMenuBar1.add(jMenuCuenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.dispose();
        PantallaLogin p = new PantallaLogin();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestorActionPerformed
        
    }//GEN-LAST:event_jMenuGestorActionPerformed

    private void jMenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutorActionPerformed
        PanelAutor jp = new PanelAutor();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuItemAutorActionPerformed

    private void jMenuItemLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibrosActionPerformed
        PanelLibro jp = new PanelLibro();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuItemLibrosActionPerformed

    private void jMenuItemDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDistribuidorActionPerformed
        PanelDistribuidor jp = new PanelDistribuidor();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
        
    }//GEN-LAST:event_jMenuItemDistribuidorActionPerformed

    private void jMenuFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFacturasActionPerformed
        //
    }//GEN-LAST:event_jMenuFacturasActionPerformed

    private void jMenuItemFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacturaActionPerformed
     
    }//GEN-LAST:event_jMenuItemFacturaActionPerformed

    private void jMenuMantenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMantenedorActionPerformed
        PanelMantenedor jp = new PanelMantenedor();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuMantenedorActionPerformed

    private void jMenuItemMantenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMantenedorActionPerformed
        PanelMantenedor jp = new PanelMantenedor();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuItemMantenedorActionPerformed

    private void jMenuItemEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditorialActionPerformed
        PanelEditorial jp = new PanelEditorial();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuItemEditorialActionPerformed

    private void jMenuItemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroActionPerformed
   
    }//GEN-LAST:event_jMenuItemRegistroActionPerformed

    private void jMenuItemAdminLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminLibrosActionPerformed
        PanelLibrosBiblioteca jp = new PanelLibrosBiblioteca();
        this.setLayout(null);
        jp.setSize(800,570);
        jPanelContenido.removeAll();
        jPanelContenido.add(jp, BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jMenuItemAdminLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCuenta;
    private javax.swing.JMenu jMenuFacturas;
    private javax.swing.JMenu jMenuGestor;
    private javax.swing.JMenuItem jMenuItemAdminLibros;
    private javax.swing.JMenuItem jMenuItemAutor;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemDistribuidor;
    private javax.swing.JMenuItem jMenuItemEditorial;
    private javax.swing.JMenuItem jMenuItemFactura;
    private javax.swing.JMenuItem jMenuItemLibros;
    private javax.swing.JMenuItem jMenuItemMantenedor;
    private javax.swing.JMenuItem jMenuItemRegistro;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuMantenedor;
    private javax.swing.JPanel jPanelContenido;
    // End of variables declaration//GEN-END:variables
}
